name: prestoncarter.com
favicon: null
layout_spectrum: 0.16036154399625957
typography_spectrum: 0.3263664327096194
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5292777977883816
  lightness: 0.37513958336785436
  saturation: 0.03198334015905857
  rhythmicContrast: 0.5194076891057193
purpose: []
